### ISSUE TITLE
Everything is showing Inactive

### ISSUE THREAD

**Issue by audiodk** [mathhulk/advancedbans#56]
Hello I am trying to build off of your source a little and i am having a problem with everything showing Inactive when the Ban is actually Active.  Could you point me into the right direction to fix this please?

Here is a screen shot:
![image](https://user-images.githubusercontent.com/7694623/49090345-809ba680-f22b-11e8-97f1-c36275704ba1.png)
This entry should be showing Active

**Comment by audiodk** [comment]
Can anyone help with this?

**Comment by audiodk** [comment]
yea I am sure.  I can ban someone and the site will still show it inactive

**Comment by winnipeg21** [comment]
Go update the panel to the latest version, that should fix it

**Comment by winnipeg21** [comment]
Was your issue resolved?

**Comment by audiodk** [comment]
no.  Not sure what is going on.  I am comparing the codes to see if i messed something up somewhere

**Comment by winnipeg21** [comment]
Did you reinstall the panel to the latest version?

**Comment by audiodk** [comment]
I tried to once but it wasn't working for me.  I will try it again though. Audio Founder/CEO Generations Network ---- On Wed, 12 Dec 2018 18:46:23 -0500 Robert <notifications@github.com> wrote ---- Did you reinstall the panel to the latest version? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mathhulk** [comment]
I will look into the update as soon as I can. However, the issue should have been fixed fairly recently.

**Comment by audiodk** [comment]
thank you

**Comment by mathhulk** [comment]
No problem! Let me know because I have been trying to get updates pushed out for fixes.

**Comment by audiodk** [comment]
Everything is still showing Inactive for me.  I just tried doing a clone of your repository and the same thing with that.

**Comment by mathhulk** [comment]
I've noticed the issue and I will look into fixing this as soon as possible @audiodk. Thanks!

**Comment by audiodk** [comment]
yes everything shows as Inactive no matter if its a mute or ban or anything

**Comment by mathhulk** [comment]
Thank you. I will look into this.

**Comment by bloodyearth** [comment]
I have the same problem

**Comment by mathhulk** [comment]
Should be fixed in the latest update.
